name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dipatch:

jobs:
  test:
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        otp: ["25.0.4"]
        elixir: ["1.14.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: CargoSense/setup-elixir-project@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          build-flags: "--warnings-as-errors"
      - run: mix format --check-formatted
      - run: mix test
